### ISSUE TITLE
第一个issues，版本号呢？

### ISSUE THREAD

**Issue by zhangkevd** [bytedance/BoostMultiDex#1]
第一个issues，我来占个坑哈
`
dependencies {
... ...
    implementation 'com.bytedance.boost_multidex:boost_multidex:${ARTIFACT_VERSION}'
}
`
ARTIFACT_VERSION 版本是多少？放在哪个仓库里面？maven里没有

**Comment by Leonw2229** [comment]
是啊，我本来看到文章想用上试试看效果呢，谁知道进来没看到版本号，太刺激了；难道要用手动编译那个办法吗

**Comment by Leonw2229** [comment]
看到了。1.0.0；在app的build.gradle里面🈶
