### ISSUE TITLE
4.3系统上导致Arouter不能正常记性跳转

### ISSUE THREAD

**Issue by zeuscode** [bytedance/BoostMultiDex#12]

**Comment by GalaxyLeo** [comment]
完整日志补充一下？
理论上不影响的

**Comment by GalaxyLeo** [comment]
完整日志补充一下？
理论上不影响的

**Comment by GalaxyLeo** [comment]
完整日志补充一下？
理论上不影响的

**Comment by crzaycat** [comment]
在极少部分手机上接入BoostMultiDex会导致Arouter找不到路径，我这边的项目，在云测上，android 4.4.4的三星 SM-G5308W 会出现这问题
