### ISSUE TITLE
Monitor.doAfterInstall里面的Looper.myQueue()是否换成MainLooper更好？

### ISSUE THREAD

**Issue by initialjie** [bytedance/BoostMultiDex#19]
场景是打算在子线程调用BoostMultiDex.install，但是文档未告知目前只能在UI线程调用，或者含有looper的线程调用

**Comment by GalaxyLeo** [comment]
Monitor.doAfterInstall是可以覆写的，然后再通过`BoostMultiDex.install(Context context, Monitor monitor)`传入即可。
