### ISSUE TITLE
集成之后，页面跳转不了

### ISSUE THREAD

**Issue by ansonxia** [bytedance/BoostMultiDex#25]
我们的项目页面间跳转是使用的阿里路由跳转（com.alibaba:arouter-api:1.5.2），因为在Android4.4 上启动慢，所以想尝试boost方案，但是发现，只能停留在启动页，跳转报路由找不到。
从日志看ARouter::(17966): Filter 0 classes by packageName <com.alibaba.android.arouter.routes>，正常启动的日志应该是
Filter 73 classes by packageName <com.alibaba.android.arouter.routes>

**Comment by ansonxia** [comment]
已解决

**Comment by zejunzhang** [comment]
@ansonxia 你好，想请问怎么解决的 我也遇到了这个问题，谢谢

**Comment by ansonxia** [comment]
hI:

  工程目录： classpath "com.alibaba:arouter-register:1.0.2"

   model:   apply plugin:'com.alibaba.arouter'













在 2024-10-31 18:44:35，"zejunzhang" ***@***.***> 写道：

@ansonxia 你好，想请问怎么解决的 我也遇到了这个问题，谢谢
