### ISSUE TITLE
征文 | Call for articles

### ISSUE THREAD

**Issue by GalaxyLeo** [bytedance/BoostMultiDex#8]
欢迎大家贡献本项目的深度分析好文。可以是接入自己工程的深度体验，或者本项目源码分析，我们将选取优秀文章放到[Wiki](https://github.com/bytedance/BoostMultiDex/wiki/Technical-Article)中。

可以在评论区贴上文章链接，或者发送到邮箱xiaolin.gan@bytedance.com与我们联系。谢谢。

---

Everyone is welcome to contribute in-depth analysis of this project. It can be the in-depth experience of accepting your own project, or the source code analysis of this project. We will select excellent articles to [Wiki](https://github.com/bytedance/BoostMultiDex/wiki/Technical-Article).

You can post a link to the article in the comment area, or send it to xiaolin.gan@bytedance.com to contact us. Thank you.

**Comment by SmallBlueWhale** [comment]
4.4以下的手机这么少，为啥要花大力气做收益小的事情，单纯吐槽。

**Comment by DysaniazzZ** [comment]
> 4.4以下的手机这么少，为啥要花大力气做收益小的事情，单纯吐槽。

手机上虽然 5.0 一下的很少了，而且国民应用微信的的最小兼容版本都是 API 21 了。但是电视上，4.4 及以下的设备还有很多很多，办宽带移动送的魔百盒都是 4.4 系统。

**Comment by GalaxyLeo** [comment]
转移到Discussions区
