### ISSUE TITLE
在后面的版本可以支持 arm64-v8a的so库吗？

### ISSUE THREAD

**Issue by funnyzhaov** [bytedance/BoostMultiDex#9]
我们的应用在Google Play上架，Google Play要求需要支持arm64-v8a的架构，目前1.0.1版本不支持，导致用户Crash了，
希望可以支持一下。

**Comment by GalaxyLeo** [comment]
Dalvik虚拟机下只需要支持32位的，如果64位机型一定是5.0以上手机，这种情况我们会直接跳过。所以你这个崩溃应该是其他原因导致的吧

**Comment by funnyzhaov** [comment]
嗯，是Fresco加载自己的so库报的错误，我们打包出来，发现armeabi-v7a下有BoostMultiDex的so,而arm64-v8a里没有。
查了下文档说是如果同时支持的架构里有arm64-v8a，那么arm64-v8a里的so应该和armeabi-v7a里的保持一致。
因此推测是BoostMultiDex不支持arm64-v8a的so导致的。

**Comment by funnyzhaov** [comment]
> Dalvik虚拟机下只需要支持32位的，如果64位机型一定是5.0以上手机，这种情况我们会直接跳过。所以你这个崩溃应该是其他原因导致的吧

跳过的逻辑在哪一块处理？哪一个类，我想参考一下

**Comment by KnIfER** [comment]
没有 64 位的库，会导致没有自己so库的纯java自动切换为加载32位的库，连累 createPackageContext  插件式调用也无法加载 64 位的库。开发跑路了吗，建议包含64位的so，即使占位也好。

后来我自己创建了个0kb的so放到main/jniLibs/arm64-v8a 文件夹。。
